/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { BasicNFT__factory } from "./BasicNFT__factory";
export { BasicNft__factory } from "./BasicNft__factory";
