/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { BasicNFT__factory } from "./BasicNFT__factory";
export { RandomIPFSNFT__factory } from "./RandomIPFSNFT__factory";
